/* version.c */
/* Autogenerated by Makefile - DO NOT EDIT */

const char *version_string = "1.16";
const char *compilation_string = "gcc -DHAVE_CONFIG_H -DSYSTEM_WGETRC=\"/opt/wget/etc/wgetrc\" -DLOCALEDIR=\"/opt/wget/share/locale\" -I. -I../lib -I../lib -g -O2";
const char *link_string = "gcc -g -O2 -lssl -lcrypto -ldl -lz -lidn -luuid ftp-opie.o openssl.o http-ntlm.o ../lib/libgnu.a";
